### ISSUE TITLE
Présenter les pistes sous forme de modules verticaux

### ISSUE THREAD

**Issue by Asdivecci** [Utrope/utrope.github.io#14]
Préparer un module modèle avec les fonctions déjà installées <mute> <solo> <play/pause> <stop> <volume> <select [level>.]

Inspiration : (https://docs.google.com/drawings/d/1m-jr4RXZuyfONfIiBBzvRj95s-Udm3BKb7B_vstuOIM/edit)

Ce qui est appelé module correspond au rectangle Vert sur le draw du lien précédent et correspond à un instrument.

Ce module modèle doit pouvoir être copié/collé par la suite pour obtenir un morceau.

**Comment by Utrope** [comment]
cliquer sur un bouton le remplit / blanchit
