### ISSUE TITLE
Pouvoir relancer les pistes une fois qu'elles sont terminées

### ISSUE THREAD

**Issue by Asdivecci** [Utrope/utrope.github.io#3]
Une fois le morceau fini, il faut pouvoir relancer les pistes depuis le début en cliquant sur "jouer les pistes"

**Comment by Utrope** [comment]
chez moi ça fonctionne bien, donc je comprends pas trop

**Comment by Utrope** [comment]
ok

**Comment by Utrope** [comment]
à tester, fix fait

**Comment by Asdivecci** [comment]
C'est parfait ici
