### ISSUE TITLE
Changement de morceau - passage à Glao

### ISSUE THREAD

**Issue by Utrope** [Utrope/utrope.github.io#33]
passage à Glao

**Comment by Asdivecci** [comment]
Tranches à préparer : 
- Batterie (4 niveaux)
- Basse (3 niveaux)
- Guitare (3 niveaux)
- Claviers (3 niveaux)
- Cuivre 1 (3 instruments x 3 niveaux)
- Cuivre 2 (3 instruments x 3 niveaux)
- Prod (2 pistes)
